-- 0000_base_schema.sql
--
-- RECONSTRUCTED base schema for the two tables that predate this migrations
-- folder: `products` and `orders`. They were originally created through the
-- Supabase dashboard, so there was no migration file for them -- which means
-- a fresh or staging project could not be reproduced from `supabase/migrations/`
-- alone. This file closes that gap.
--
-- VERIFICATION STATUS (2026-08-29):
--   Verified against the LIVE database via `information_schema.columns`,
--   `information_schema.table_constraints` and `pg_indexes` (the Supabase CLI
--   `db pull` / `db dump` both need Docker, which isn't set up here, so SQL
--   introspection was used instead). For the pre-0001 column subset below,
--   column names, types, nullability and defaults now MATCH the live schema
--   exactly. Corrections made from the earlier best-effort guess:
--     * identity is GENERATED BY DEFAULT, not ALWAYS
--     * products.images is text[]  (was guessed jsonb)
--     * products.inventory is bigint, nullable, no default
--       (was guessed integer not null default 0)
--     * products.name / products.price are nullable (were guessed not null)
--     * orders.order_id / payment_id / amount are nullable (were guessed not null)
--   The dashboard-created tables are deliberately permissive: almost nothing
--   is NOT NULL and there are no column defaults beyond created_at. That is
--   the real production state, not a reconstruction shortcut -- the app code
--   is what enforces "price must exist", "inventory defaults to 0", etc.
--
-- NOTES:
--   * Every statement is `IF NOT EXISTS`, so running this against the existing
--     production database is a safe no-op.
--   * This file represents the schema as it stood BEFORE migration 0001.
--     Columns added later (orders.status / awb_number / shipping_address,
--     products.category / display_order / dimensions / cost_price / hidden /
--     ...), every index, the orders.status CHECK, the
--     orders_payment_id_key UNIQUE (0037), and all RLS live in 0001..0042 and
--     must be run after this, in order.
--   * Column order below matches live ordinal position so a fresh bootstrap
--     (0000 then 0001+ appending) ends up column-for-column identical to prod.

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------
create table if not exists products (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text,
  price       numeric,
  description text,
  image_url   text,
  inventory   bigint,          -- nullable in prod; app coerces null -> 0
  images      text[]           -- gallery paths; nullable, no default
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
create table if not exists orders (
  id               bigint generated by default as identity primary key,
  created_at       timestamptz not null default now(),
  order_id         text,            -- Razorpay order id (order_...)
  payment_id       text,            -- Razorpay payment id; UNIQUE constraint added in 0037
  amount           numeric,
  customer_details jsonb,           -- { email, contact, name }
  items            jsonb            -- [{ id, name, price, quantity, gstRate, image_url, category }]
);

-- RLS is intentionally NOT configured here -- before migration 0003 it was
-- off on these tables. It is enabled and locked down in 0003 / 0039 / 0040.
