-- 0043_add_stock_reservations.sql
-- Short-TTL stock reservation at checkout (IMPROVEMENTS.md Tier 1 #1).
-- Closes the last order-path correctness gap: today stock is only
-- decremented AFTER payment (in /api/razorpay-webhook via
-- decrement_inventory, 0041), so two shoppers can both pass the
-- `qty <= inventory` read in /api/razorpay and both pay for the last unit.
-- This holds the stock for the duration of a checkout so the second
-- shopper is stopped at /api/razorpay, before a payable order exists.
--
-- Design + failure-mode analysis: docs/DESIGN-stock-reservation.md.
-- Purely additive. Nothing about 0041 / 0042 / the orders table changes.
-- Ships DISABLED (site_settings.stock_reservations_enabled = '0'); flip it
-- to '1' from the admin Settings tab once the SQL checks below pass.
--
-- Same inherited-grant gotcha as 0041/0042: `revoke ... from public` also
-- strips service_role's inherited EXECUTE, so it must be re-granted
-- explicitly.

create table if not exists stock_reservations (
  id             bigint generated by default as identity primary key,
  checkout_token uuid not null,
  product_id     bigint not null,
  qty            integer not null check (qty > 0),
  status         text not null default 'held'
                 check (status in ('held', 'consumed', 'released')),
  expires_at     timestamptz not null,
  created_at     timestamptz not null default now()
);

-- Availability sum: held + unexpired, by product (partial index).
create index if not exists stock_reservations_active_idx
  on stock_reservations (product_id)
  where status = 'held';
-- Lookup / release / consume by token.
create index if not exists stock_reservations_token_idx
  on stock_reservations (checkout_token);
-- Daily hygiene trim of stale rows (the abandoned-checkout cron).
create index if not exists stock_reservations_expires_idx
  on stock_reservations (expires_at);

alter table stock_reservations enable row level security;
-- No policy -- service-role only, like every other table in this schema.
-- The anon/publishable key must never see reservation data.

-- ---------------------------------------------------------------------------
-- reserve_stock(token, items, ttl_seconds)
--   items: jsonb array of { id | product_id, quantity }
--   returns exactly one row:
--     ok = true                                  -> every line reserved
--     ok = false, product_id/name/available set  -> that line was short;
--                                                   NOTHING was inserted
--
-- Two passes so it's genuinely all-or-nothing without needing to raise:
--   pass 1 locks every product row (FOR UPDATE, serialises concurrent
--          reservers -- same strategy as decrement_inventory) and checks
--          availability; on the first shortfall it returns ok=false having
--          inserted nothing.
--   pass 2 (only reached if every line fits) inserts the held rows. The
--          pass-1 locks are still held, so no concurrent reserver can slip
--          in between the check and the insert.
-- ---------------------------------------------------------------------------
create or replace function reserve_stock(
  p_token uuid,
  p_items jsonb,
  p_ttl_seconds integer
)
returns table (ok boolean, product_id bigint, product_name text, available integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item   jsonb;
  v_pid    bigint;
  v_qty    integer;
  v_inv    bigint;
  v_name   text;
  v_held   bigint;
  v_avail  bigint;
begin
  -- Pass 1: lock + check, insert nothing.
  for v_item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    v_pid := coalesce((v_item->>'id')::bigint, (v_item->>'product_id')::bigint);
    v_qty := coalesce((v_item->>'quantity')::integer, 0);
    if v_pid is null or v_qty <= 0 then
      continue;
    end if;

    select p.inventory, p.name into v_inv, v_name
      from products p where p.id = v_pid for update;

    if not found then
      -- Product vanished (deleted / hidden filter upstream) -- treat as 0.
      return query select false, v_pid, coalesce(v_name, v_pid::text), 0;
      return;
    end if;

    select coalesce(sum(r.qty), 0) into v_held
      from stock_reservations r
      where r.product_id = v_pid
        and r.status = 'held'
        and r.expires_at > now();

    v_avail := coalesce(v_inv, 0) - v_held;
    if v_avail < v_qty then
      return query select false, v_pid, coalesce(v_name, v_pid::text),
                          greatest(v_avail, 0)::integer;
      return;
    end if;
  end loop;

  -- Pass 2: every line fit -- insert the holds.
  for v_item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    v_pid := coalesce((v_item->>'id')::bigint, (v_item->>'product_id')::bigint);
    v_qty := coalesce((v_item->>'quantity')::integer, 0);
    if v_pid is null or v_qty <= 0 then
      continue;
    end if;

    insert into stock_reservations (checkout_token, product_id, qty, expires_at)
    values (p_token, v_pid, v_qty,
            now() + make_interval(secs => greatest(p_ttl_seconds, 1)));
  end loop;

  return query select true, null::bigint, null::text, null::integer;
end;
$$;

-- ---------------------------------------------------------------------------
-- consume_reservation(token)
--   For each still-held row on the token: row-lock the product, decrement
--   (clamped at 0), mark the reservation 'consumed', and return
--   (product_id, new_inventory, oversold_by) -- same shape decrement_inventory
--   returns, so the webhook's oversell / low-stock alert logic is unchanged.
--   Returns NO rows if the token has no held rows (expired + trimmed, or a
--   duplicate webhook already consumed it) -- the caller then falls back to
--   the legacy per-item decrement_inventory loop over notes.items.
-- ---------------------------------------------------------------------------
create or replace function consume_reservation(p_token uuid)
returns table (product_id bigint, new_inventory integer, oversold_by integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row   record;
  v_inv   bigint;
  v_new   bigint;
begin
  for v_row in
    select r.id, r.product_id, r.qty
      from stock_reservations r
      where r.checkout_token = p_token
        and r.status = 'held'
      for update
  loop
    select p.inventory into v_inv from products p where p.id = v_row.product_id for update;
    if not found then
      update stock_reservations set status = 'consumed' where id = v_row.id;
      continue;
    end if;

    v_new := greatest(0, coalesce(v_inv, 0) - v_row.qty);
    update products set inventory = v_new where id = v_row.product_id;
    update stock_reservations set status = 'consumed' where id = v_row.id;

    product_id   := v_row.product_id;
    new_inventory := v_new::integer;
    oversold_by  := greatest(0, v_row.qty - coalesce(v_inv, 0))::integer;
    return next;
  end loop;
end;
$$;

-- Grants: revoke the inherited public EXECUTE, re-grant service_role
-- explicitly (0041/0042 gotcha).
revoke all on function reserve_stock(uuid, jsonb, integer) from public, anon, authenticated;
grant execute on function reserve_stock(uuid, jsonb, integer) to service_role;
revoke all on function consume_reservation(uuid) from public, anon, authenticated;
grant execute on function consume_reservation(uuid) to service_role;

-- Kill switch. Ship OFF; flip to '1' from the admin Settings tab (no
-- redeploy) once the checks below pass.
insert into site_settings (key, value)
values ('stock_reservations_enabled', '0')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------------
-- Verification (run against the live DB, like the 0041/0042 checks):
--
--   -- EXECUTE is service_role-only:
--   select proname, proacl from pg_proc
--    where proname in ('reserve_stock','consume_reservation');
--
--   -- reserve then check the availability sum reflects it:
--   select * from reserve_stock('00000000-0000-0000-0000-000000000001',
--     '[{"id": <PID>, "quantity": 1}]'::jsonb, 900);
--   select coalesce(sum(qty),0) from stock_reservations
--    where product_id = <PID> and status='held' and expires_at > now();
--
--   -- a second reserve over the remainder -> ok=false, no new row:
--   select * from reserve_stock('00000000-0000-0000-0000-000000000002',
--     '[{"id": <PID>, "quantity": 999}]'::jsonb, 900);
--
--   -- an expired hold is ignored by the sum (set expires_at into the past).
--
--   -- consume decrements inventory + flips the row to 'consumed':
--   select * from consume_reservation('00000000-0000-0000-0000-000000000001');
--
--   -- consume on an unknown token returns 0 rows (caller falls back).
--
--   -- cleanup:
--   delete from stock_reservations
--    where checkout_token in ('00000000-0000-0000-0000-000000000001',
--                             '00000000-0000-0000-0000-000000000002');
-- ---------------------------------------------------------------------------
