-- 0063_add_gift_campaigns.sql
-- "Gift With Purchase" campaigns (IMPROVEMENTS.md marketing backlog): an
-- admin-configured promotion -- pick a product, a minimum order amount, a
-- maximum redemption count, and a start/end window -- that grants the first
-- N qualifying prepaid orders a free unit of that product as an extra
-- ₹0 line item.
--
-- Deliberately a real table, not a single site_settings JSON blob like
-- spend_tier_offer / featured_spotlight: this needs a hard redemption cap
-- enforced under concurrency (the gift product is also sold at full price,
-- so its own inventory can't double as the cap), which isn't safely
-- expressible against a JSON blob, and the owner wants to run multiple
-- campaigns over time with visible history, which a single overwritten
-- blob can't hold either.
--
-- gift_campaign_claims mirrors stock_reservations' held/consumed/released
-- lifecycle (0043) exactly, keyed by the same checkout_token, for the same
-- reason stock needed a ledger table rather than a bare counter column:
-- a "hold" has to survive the gap between order-creation (claim) and
-- payment-capture (consume) or explicit cancellation (release) -- separate
-- transactions, so a single row's redeemed_count can't represent
-- in-flight-but-unpaid claims on its own.
--
-- Same inherited-grant gotcha as 0041/0042/0043: `revoke ... from public`
-- also strips service_role's inherited EXECUTE, so it must be re-granted
-- explicitly.

create table if not exists gift_campaigns (
  id              bigint generated by default as identity primary key,
  enabled         boolean not null default false,
  title           text not null,
  gift_product_id bigint not null references products(id),
  min_amount      numeric not null check (min_amount > 0),
  max_redemptions integer not null check (max_redemptions > 0),
  -- Consumed (paid) redemptions only -- in-flight holds live in
  -- gift_campaign_claims below, not counted here until consumed.
  redeemed_count  integer not null default 0 check (redeemed_count >= 0),
  starts_at       timestamptz,       -- null = active as soon as enabled
  ends_at         timestamptz not null, -- required -- see the sanitiser: a
                                         -- campaign needs a definite close
  created_at      timestamptz not null default now()
);

-- Read-path lookup: "the" active campaign, soonest-ending first if somehow
-- more than one is enabled+in-window (see app/utils/giftCampaigns.ts --
-- deliberately not blocked at write time, resolved deterministically here).
create index if not exists gift_campaigns_active_idx
  on gift_campaigns (enabled, ends_at);

alter table gift_campaigns enable row level security;
-- No policy -- service-role only, like every other table in this schema.

create table if not exists gift_campaign_claims (
  id             bigint generated by default as identity primary key,
  campaign_id    bigint not null references gift_campaigns(id) on delete cascade,
  checkout_token uuid not null,
  status         text not null default 'held'
                 check (status in ('held', 'consumed', 'released')),
  expires_at     timestamptz not null,
  created_at     timestamptz not null default now()
);

-- At most one HELD claim per checkout token -- a retried /api/razorpay call
-- for the same in-flight checkout must not stack a second hold.
create unique index if not exists gift_campaign_claims_token_held_idx
  on gift_campaign_claims (checkout_token) where status = 'held';
-- Availability count: held + unexpired, by campaign (mirrors
-- stock_reservations_active_idx).
create index if not exists gift_campaign_claims_active_idx
  on gift_campaign_claims (campaign_id) where status = 'held';
-- Lookup by token for consume/release.
create index if not exists gift_campaign_claims_token_idx
  on gift_campaign_claims (checkout_token);
-- Daily hygiene trim of stale rows (the abandoned-checkout cron, table
-- hygiene only -- an expired 'held' row is already excluded from the
-- availability count by claim_gift_campaign_slot's own expires_at filter).
create index if not exists gift_campaign_claims_expires_idx
  on gift_campaign_claims (expires_at);

alter table gift_campaign_claims enable row level security;
-- No policy -- service-role only.

-- ---------------------------------------------------------------------------
-- claim_gift_campaign_slot(campaign_id, token, ttl_seconds)
--   Locks the campaign row (FOR UPDATE, same serialising strategy as
--   reserve_stock), counts currently-held unexpired claims for it, and
--   rejects if redeemed_count + held_count would meet-or-exceed
--   max_redemptions. Otherwise inserts a 'held' claim and returns ok=true.
--   Returns exactly one row: (ok boolean).
-- ---------------------------------------------------------------------------
create or replace function claim_gift_campaign_slot(
  p_campaign_id bigint,
  p_token uuid,
  p_ttl_seconds integer
)
returns table (ok boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign gift_campaigns%rowtype;
  v_held     bigint;
begin
  select * into v_campaign from gift_campaigns where id = p_campaign_id for update;
  if not found then
    return query select false;
    return;
  end if;

  select count(*) into v_held
    from gift_campaign_claims c
    where c.campaign_id = p_campaign_id
      and c.status = 'held'
      and c.expires_at > now();

  if v_campaign.redeemed_count + v_held >= v_campaign.max_redemptions then
    return query select false;
    return;
  end if;

  insert into gift_campaign_claims (campaign_id, checkout_token, expires_at)
  values (p_campaign_id, p_token, now() + make_interval(secs => greatest(p_ttl_seconds, 1)));

  return query select true;
end;
$$;

-- ---------------------------------------------------------------------------
-- consume_gift_campaign_claim(token)
--   On confirmed payment: flips the matching 'held' claim to 'consumed' AND
--   increments the parent campaign's redeemed_count, atomically, in one
--   statement per table. No-ops (returns false) if the token has no held
--   claim -- a duplicate webhook delivery, an already-consumed claim, or a
--   checkout that was never granted a gift in the first place.
-- ---------------------------------------------------------------------------
create or replace function consume_gift_campaign_claim(p_token uuid)
returns table (ok boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id bigint;
begin
  update gift_campaign_claims
     set status = 'consumed'
   where checkout_token = p_token
     and status = 'held'
  returning campaign_id into v_campaign_id;

  if v_campaign_id is null then
    return query select false;
    return;
  end if;

  update gift_campaigns set redeemed_count = redeemed_count + 1 where id = v_campaign_id;

  return query select true;
end;
$$;

-- Grants: revoke the inherited public EXECUTE, re-grant service_role
-- explicitly (0041/0042/0043 gotcha).
revoke all on function claim_gift_campaign_slot(bigint, uuid, integer) from public, anon, authenticated;
grant execute on function claim_gift_campaign_slot(bigint, uuid, integer) to service_role;
revoke all on function consume_gift_campaign_claim(uuid) from public, anon, authenticated;
grant execute on function consume_gift_campaign_claim(uuid) to service_role;

-- ---------------------------------------------------------------------------
-- Verification (run against the live DB, like the 0043 checks):
--
--   -- EXECUTE is service_role-only:
--   select proname, proacl from pg_proc
--    where proname in ('claim_gift_campaign_slot','consume_gift_campaign_claim');
--
--   -- create a tiny test campaign (replace <PID> with a real product id):
--   insert into gift_campaigns (enabled, title, gift_product_id, min_amount, max_redemptions, ends_at)
--   values (true, 'test', <PID>, 100, 1, now() + interval '1 day')
--   returning id; -- note the id as <CID>
--
--   -- first claim succeeds:
--   select * from claim_gift_campaign_slot(<CID>, '00000000-0000-0000-0000-000000000001', 900);
--   -- a second claim while the cap is already met (max_redemptions=1) fails:
--   select * from claim_gift_campaign_slot(<CID>, '00000000-0000-0000-0000-000000000002', 900);
--
--   -- consuming the first claim increments redeemed_count:
--   select * from consume_gift_campaign_claim('00000000-0000-0000-0000-000000000001');
--   select redeemed_count from gift_campaigns where id = <CID>; -- expect 1
--
--   -- consuming an unknown/already-consumed token returns ok=false:
--   select * from consume_gift_campaign_claim('00000000-0000-0000-0000-000000000001');
--
--   -- cleanup:
--   delete from gift_campaigns where id = <CID>; -- cascades the claims
-- ---------------------------------------------------------------------------
